name: 🚀 Feature request
description: Suggest a new feature and help us improve 🙂
labels: ["enhancement"]
body:
  - type: textarea
    id: feature-description
    attributes:
      label: Describe the feature
      description: Please provide a clear and concise description of the feature you are requesting.
      placeholder: Feature description
    validations:
      required: true
  - type: textarea
    id: suggested-solution
    attributes:
      label: Suggested solution
      description: Please provide a clear and concise description of the solution you are proposing for the requested feature.
      placeholder: Suggested solution
    validations:
      required: true
  - type: textarea
    id: alternative
    attributes:
      label: Alternative
      description: Please provide a clear and concise description of any alternative solutions or features you have considered.
      placeholder: Alternative
    validations:
      required: false
  - type: checkboxes
    id: validations
    attributes:
      label: Validations
      description: Before submitting the issue, please make sure you do the following.
      options:
        - label: Read the [contributing guidelines](https://github.com/ogea12/.github/blob/master/CONTRIBUTING.md).
          required: true
        - label: Check that there isn't already an issue that requests the same feature to avoid creating a duplicate.
          required: true
